services:
    dante:
        container_name: my_dante
        restart: always
        image: adegtyarev/dante
        command: sockd-username
        environment:
            SOCKD_USER_NAME: user123
            SOCKD_USER_PASSWORD: pass123
        ports:
            - 6363:1080
        volumes:
            - ./sockd.conf:/etc/sockd.conf

